import React, { useState, useEffect } from 'react';
import { Card } from '../UI/Card';
import { Button } from '../UI/Button';
import { Download, FileSpreadsheet, Upload, AlertCircle } from 'lucide-react';
import { utils, writeFile, read } from 'xlsx';
import { SalaryRecord, Site } from '../../types';
import { dbService } from '../../services/mockDb';

interface SalaryProcessingProps {
  showNotification: (type: 'success' | 'error', msg: string) => void;
}

export const SalaryProcessing: React.FC<SalaryProcessingProps> = ({ showNotification }) => {
  const [sites, setSites] = useState<Site[]>([]);
  const [selectedSiteId, setSelectedSiteId] = useState('');
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  
  const [salaryFile, setSalaryFile] = useState<File | null>(null);
  const [uploadStatus, setUploadStatus] = useState('');
  const [isUploading, setIsUploading] = useState(false);

  useEffect(() => {
      const loadSites = async () => {
          const data = await dbService.getAllSites();
          setSites(data);
          if (data.length > 0) setSelectedSiteId(data[0].id);
      };
      loadSites();
  }, []);

  const downloadTemplate = () => {
    const headers = ['UAN', 'Basic', 'HRA', 'Allowances', 'PF_Deduction', 'Tax_Deduction'];
    const ws = utils.aoa_to_sheet([headers]);
    const wb = utils.book_new();
    utils.book_append_sheet(wb, ws, "Salary_Template");
    writeFile(wb, "Konark_Salary_Template.xlsx");
  };

  const handleSalaryUpload = async () => {
      if (!salaryFile || !selectedSiteId) return;
      
      setIsUploading(true);
      setUploadStatus('Processing file...');
      try {
          const ab = await salaryFile.arrayBuffer();
          const wb = read(ab);
          const sheet = wb.Sheets[wb.SheetNames[0]];
          if (!sheet) throw new Error("No sheet found in Excel file");

          const data = utils.sheet_to_json(sheet) as any[];
          
          const records: SalaryRecord[] = [];
          const invalidUans: string[] = [];

          // Safe Parsing Helper
          const parseNum = (val: any) => {
              const n = parseFloat(val);
              return isNaN(n) ? 0 : n;
          };

          for (const row of data) {
              const uan = row.UAN ? String(row.UAN).trim() : '';
              
              if (!/^\d{12}$/.test(uan)) {
                  if(uan) invalidUans.push(uan);
                  continue;
              }
              
              records.push({
                  id: '', // Generated by DB
                  employeeUan: uan,
                  siteId: selectedSiteId, // Linked to selected site
                  month: selectedMonth,   // Linked to selected month
                  year: selectedYear,     // Linked to selected year
                  basic: parseNum(row.Basic),
                  hra: parseNum(row.HRA),
                  allowances: parseNum(row.Allowances),
                  pfDeduction: parseNum(row.PF_Deduction),
                  taxDeduction: parseNum(row.Tax_Deduction),
                  netSalary: 0, // Calculated by DB
                  isLocked: true
              });
          }

          if (records.length > 0) {
              const { processed } = await dbService.uploadSalaryData(records, 'HR_ADMIN');
              setUploadStatus(`Success: ${processed} records processed for site. ${invalidUans.length > 0 ? `${invalidUans.length} skipped.` : ''}`);
              showNotification('success', "Salary batch processed successfully.");
          } else {
              setUploadStatus("No valid records found in file.");
              showNotification('error', "File contained no valid records.");
          }
      } catch (e: any) {
          setUploadStatus("Upload Failed: " + e.message);
          showNotification('error', "Upload failed.");
      } finally {
          setIsUploading(false);
          setSalaryFile(null);
      }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6 animate-fade-in">
        
        {/* Context Selection Card */}
        <Card title="1. Select Context" className="p-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                    <label className="block text-xs font-bold text-slate-500 mb-2 uppercase">Site</label>
                    <select 
                        className="w-full p-2.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm"
                        value={selectedSiteId}
                        onChange={e => setSelectedSiteId(e.target.value)}
                    >
                        {sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                    </select>
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 mb-2 uppercase">Month</label>
                    <select 
                        className="w-full p-2.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm"
                        value={selectedMonth}
                        onChange={e => setSelectedMonth(parseInt(e.target.value))}
                    >
                        {Array.from({length: 12}, (_, i) => i + 1).map(m => (
                            <option key={m} value={m}>{new Date(0, m-1).toLocaleString('default', { month: 'long' })}</option>
                        ))}
                    </select>
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 mb-2 uppercase">Year</label>
                    <select 
                        className="w-full p-2.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm"
                        value={selectedYear}
                        onChange={e => setSelectedYear(parseInt(e.target.value))}
                    >
                        {[2023, 2024, 2025].map(y => <option key={y} value={y}>{y}</option>)}
                    </select>
                </div>
            </div>
            <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 text-xs rounded-lg flex items-center gap-2">
                <AlertCircle className="w-4 h-4" />
                <span>Upload will be processed for <strong>{sites.find(s => s.id === selectedSiteId)?.name}</strong> for <strong>{selectedMonth}/{selectedYear}</strong>.</span>
            </div>
        </Card>

        {/* Upload Card */}
        <Card title="2. Upload Data" className="p-6 text-center">
            <div className="flex flex-col gap-4 max-w-sm mx-auto">
                <Button variant="outline" onClick={downloadTemplate} icon={Download}>
                    Download Template
                </Button>
                
                <div className="border-2 border-dashed border-slate-300 dark:border-slate-700 rounded-lg p-6 bg-slate-50 dark:bg-slate-800/50 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                    <input 
                        type="file" 
                        accept=".xlsx" 
                        onChange={e => setSalaryFile(e.target.files?.[0] || null)} 
                        className="block w-full text-sm text-slate-500 dark:text-slate-400
                        file:mr-4 file:py-2 file:px-4
                        file:rounded-full file:border-0
                        file:text-xs file:font-semibold
                        file:bg-blue-50 file:text-blue-700
                        dark:file:bg-blue-900/30 dark:file:text-blue-400
                        hover:file:bg-blue-100 dark:hover:file:bg-blue-900/50
                        cursor-pointer" 
                    />
                </div>

                <Button 
                    variant="primary" 
                    onClick={handleSalaryUpload} 
                    disabled={isUploading || !salaryFile || !selectedSiteId}
                    isLoading={isUploading}
                    icon={Upload}
                >
                    {isUploading ? 'Processing...' : 'Upload & Process'}
                </Button>
            </div>
            
            {uploadStatus && (
                <div className={`mt-6 text-sm font-medium p-3 rounded-lg ${uploadStatus.includes('Failed') || uploadStatus.includes('No valid') ? 'bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-400' : 'bg-green-50 text-green-600 dark:bg-green-900/20 dark:text-green-400'}`}>
                    {uploadStatus}
                </div>
            )}
        </Card>
    </div>
  );
};