import React, { useState } from 'react';
import { Card } from '../UI/Card';
import { Button } from '../UI/Button';
import { Download, FileSpreadsheet, Upload } from 'lucide-react';
import { utils, writeFile, read } from 'xlsx';
import { SalaryRecord } from '../../types';
import { dbService } from '../../services/mockDb';

interface SalaryProcessingProps {
  showNotification: (type: 'success' | 'error', msg: string) => void;
}

export const SalaryProcessing: React.FC<SalaryProcessingProps> = ({ showNotification }) => {
  const [salaryFile, setSalaryFile] = useState<File | null>(null);
  const [uploadStatus, setUploadStatus] = useState('');
  const [isUploading, setIsUploading] = useState(false);

  const downloadTemplate = () => {
    const headers = ['UAN', 'Month', 'Year', 'Basic', 'HRA', 'Allowances', 'PF_Deduction', 'Tax_Deduction'];
    const ws = utils.aoa_to_sheet([headers]);
    const wb = utils.book_new();
    utils.book_append_sheet(wb, ws, "Salary_Template");
    writeFile(wb, "Konark_Salary_Template.xlsx");
  };

  const handleSalaryUpload = async () => {
      if (!salaryFile) return;
      setIsUploading(true);
      setUploadStatus('Processing file...');
      try {
          const ab = await salaryFile.arrayBuffer();
          const wb = read(ab);
          const sheet = wb.Sheets[wb.SheetNames[0]];
          if (!sheet) throw new Error("No sheet found in Excel file");

          const data = utils.sheet_to_json(sheet) as any[];
          
          const records: SalaryRecord[] = [];
          const invalidUans: string[] = [];

          // Safe Parsing Helper
          const parseNum = (val: any) => {
              const n = parseFloat(val);
              return isNaN(n) ? 0 : n;
          };

          for (const row of data) {
              const uan = row.UAN ? String(row.UAN).trim() : '';
              
              if (!/^\d{12}$/.test(uan)) {
                  if(uan) invalidUans.push(uan);
                  continue;
              }
              
              records.push({
                  id: '', // Generated by DB
                  employeeUan: uan,
                  month: parseNum(row.Month),
                  year: parseNum(row.Year),
                  basic: parseNum(row.Basic),
                  hra: parseNum(row.HRA),
                  allowances: parseNum(row.Allowances),
                  pfDeduction: parseNum(row.PF_Deduction),
                  taxDeduction: parseNum(row.Tax_Deduction),
                  isLocked: true
              });
          }

          if (records.length > 0) {
              const count = await dbService.uploadSalaryData(records, 'HR_ADMIN');
              setUploadStatus(`Success: ${count} records processed. ${invalidUans.length > 0 ? `${invalidUans.length} skipped.` : ''}`);
              showNotification('success', "Salary batch processed successfully.");
          } else {
              setUploadStatus("No valid records found.");
              showNotification('error', "File contained no valid records.");
          }
      } catch (e: any) {
          setUploadStatus("Upload Failed: " + e.message);
          showNotification('error', "Upload failed.");
      } finally {
          setIsUploading(false);
          setSalaryFile(null);
      }
  };

  return (
    <Card className="max-w-2xl mx-auto p-8 text-center animate-fade-in">
        <div className="w-16 h-16 bg-blue-50 dark:bg-blue-900/20 rounded-full flex items-center justify-center mx-auto mb-4 text-blue-600 dark:text-blue-400">
            <FileSpreadsheet className="w-8 h-8" />
        </div>
        <h2 className="text-xl font-bold text-slate-800 dark:text-white mb-2">Bulk Salary Processing</h2>
        <p className="text-slate-500 dark:text-slate-400 mb-8 max-w-sm mx-auto">Upload an Excel sheet containing salary details mapped to 12-digit Employee UANs.</p>
        
        <div className="flex flex-col gap-4 max-w-sm mx-auto">
            <Button variant="outline" onClick={downloadTemplate} icon={Download}>
                Download Template
            </Button>
            
            <div className="border-2 border-dashed border-slate-300 dark:border-slate-700 rounded-lg p-6 bg-slate-50 dark:bg-slate-800/50 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                <input 
                    type="file" 
                    accept=".xlsx" 
                    onChange={e => setSalaryFile(e.target.files?.[0] || null)} 
                    className="block w-full text-sm text-slate-500 dark:text-slate-400
                    file:mr-4 file:py-2 file:px-4
                    file:rounded-full file:border-0
                    file:text-xs file:font-semibold
                    file:bg-blue-50 file:text-blue-700
                    dark:file:bg-blue-900/30 dark:file:text-blue-400
                    hover:file:bg-blue-100 dark:hover:file:bg-blue-900/50
                    cursor-pointer" 
                />
            </div>

            <Button 
                variant="primary" 
                onClick={handleSalaryUpload} 
                disabled={isUploading || !salaryFile}
                isLoading={isUploading}
                icon={Upload}
            >
                {isUploading ? 'Processing...' : 'Upload & Process'}
            </Button>
        </div>
        
        {uploadStatus && (
            <div className={`mt-6 text-sm font-medium p-3 rounded-lg ${uploadStatus.includes('Failed') || uploadStatus.includes('No valid') ? 'bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-400' : 'bg-green-50 text-green-600 dark:bg-green-900/20 dark:text-green-400'}`}>
                {uploadStatus}
            </div>
        )}
    </Card>
  );
};