// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aqfcbijhvdbwlqrvmrxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZmNiaWpodmRid2xxcnZtcnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyMzc1NTAsImV4cCI6MjA4MzgxMzU1MH0.4D62QYOYc-R8B2vLNbzvVxZhlVOVZkeimvnRyKPaXDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);